### ISSUE TITLE
TF2 Maps currently unplayable.

### ISSUE THREAD

**Issue by siobhan-saoirse** [siobhan-saoirse/Civilian2#12]
Since an unknown update, TF2 maps can no longer be played as you are completely unable to spawn, You are forced to spectate.
The only fix available is by playing non-TF2 maps.

**Comment by siobhan-saoirse** [comment]
This needs a fix BADLY. if it's unfixable, I might as well have to rewrite this gamemode from scratch entirely.

**Comment by Gordidian** [comment]
We understand the frustation and stress, for me its a little annoying that you can't actually play tf2 maps, but I never had a real problem with it. However its kinda odd that you can't play tf2 maps on the tf2 gamemode but yeah thats it. Im adressing the obvious but I just wanted to say that if you want to take your time to develop it we're ok with it.

**Comment by siobhan-saoirse** [comment]
This was easily fixed by removing some code from func_respawnroom. It can finally be played again.
